ALTER TABLE procedures ADD COLUMN is_promotional BOOLEAN DEFAULT FALSE;
ALTER TABLE procedures ADD COLUMN promo_price DECIMAL(10, 2) DEFAULT NULL;
ALTER TABLE procedures ADD COLUMN promo_end_date DATETIME DEFAULT NULL;
